name: Go CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubunto-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Run tests
      run: |
        cd api
        go mode init temp || true
        go test ./tests/... -v